---
# tasks file for demorole
- debug:
    var: "{{ {{ app_name }}['name'] }}"
- yum:
    name: "{{ {{ app_name }}['name'] }}"
    state: "{{ item.state }}"
- copy:
    content: "{{ item.content }}"
    dest: "{{ item.destination }}"
- service:
    name: "{{ item.name }}"
    state: started
