---
# tasks file for demorole
- debug:
    var: "{{ app_name }}"
- yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ {{ app_name }} }}"
- copy:
    content: "{{ item.content }}"
    dest: "{{ item.destination }}"
  loop: "{{ {{ app_name }} }}"
- service:
    name: "{{ item.name }}"
    state: started
  loop: "{{ {{ app_name }} }}"
