---
# tasks file for demorole
- yum:
    name: '{{ apps["{{ app_name }}"]["name"] }}'
    state: '{{ apps["{{ app_name }}"]["state"] }}'
- copy:
    content: '{{ apps["{{ app_name }}"]["content"] }}'
    dest: '{{ apps["{{ app_name }}"]["destination"] }}'
- service:
    name: '{{ apps["{{ app_name }}"]["name"] }}'
    state: started

