---
# tasks file for demorole
- debug:
    var: "{{ app_name }}"
  register: output
- yum:
    name: '{{ output["{{ app_name }}"]["name"] }}'
    state: '{{ output["{{ app_name }}"]["state"] }}'
- copy:
    content: '{{ output["{{ app_name }}"]["content"] }}'
    dest: '{{ output["{{ app_name }}"]["destination"] }}'
- service:
    name: '{{ output["{{ app_name }}"]["name"] }}'
    state: started

