---
# tasks file for demorole
- debug:
    var: "{{ app_name }}"
  register: output
- debug:
    var: output["{{ app_name }}"]['name']
- yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: '{{ output["{{app_name}}"] }}'
- copy:
    content: "{{ item.content }}"
    dest: "{{ item.destination }}"
  loop: '{{ output["{{app_name}}"]  }}'
- service:
    name: "{{ item.name }}"
    state: started
  loop: '{{ output["{{app_name}}"]  }}'
