---
# tasks file for demorole
- debug:
    var: lookup('dict', "{{ app_name }}")
  register: output

- yum:
    name: "{{ name }}"
    state: "{{ state }}"
- copy:
    content: "{{ content }}"
    dest: "{{ destination }}"
- service:
    name: "{{ name }}"
    state: started

