---
# tasks file for demorole
- debug:
    var: "{{ app_name['name'] }}"
  register: output

- yum:
    name: "{{ name }}"
    state: "{{ state }}"
- copy:
    content: "{{ content }}"
    dest: "{{ destination }}"
- service:
    name: "{{ name }}"
    state: started

