---
# tasks file for demorole
# - include_vars:
#     file: "{{ app_name }}.yml"
# - yum:
#     name: "{{ name }}"
#     state: "{{ state }}"
# - copy:
#     content: "{{ content }}"
#     dest: "{{ destination }}"

# - service:
#     name: "{{ name }}"
#     state: started

- debug:
    var: item.name
  loop:
    - "{{ apps }}"
  when:
    - item.app_name == "{{ app_name }}"
    
    
# - yum:
#     name: {{ apps["{{ app_name }}"]["name"] }}
#     state: {{ apps["{{ app_name }}"]["state"] }}
# - copy:
#     content: {{ apps["{{ app_name }}"]["content"] }}
#     dest: {{ apps["{{ app_name }}"]["destination"] }}
# - service:
#     name: {{ apps["{{ app_name }}"]["name"] }}
#     state: started

