---
# tasks file for demorole
# - include_vars:
#     file: "{{ app_name }}.yml"
# - yum:
#     name: "{{ name }}"
#     state: "{{ state }}"
# - copy:
#     content: "{{ content }}"
#     dest: "{{ destination }}"

# - service:
#     name: "{{ name }}"
#     state: started


    
    
- yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
  - "{{ apps }}"
  when: 
  - item.app_name in app_names
  
- copy:
    content: "{{ item.content }}"
    dest: "{{ item.destination }}"
  with_items:
  - "{{ apps }}"
  when: 
  - item.app_name in app_names
  
- service:
    name: "{{ item.name }}"
    state: started
  with_items:
  - "{{ apps }}"
  when: 
  - item.app_name in app_names
