
block:
  - yum:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
  - copy:
      content: "{{ item.content }}"
      dest: "{{ item.destination }}"
  - service:
      name: "{{ item.name }}"
      state: started
      
